### ISSUE TITLE
Hashtag invocation: zero results and same user agent used every time

### ISSUE THREAD

**Issue by geco** [drawrowfly/tiktok-scraper#358] opened 2020-11-12 08:59 UTC
**Describe the bug**
Hashtag invocation alway returns zero results, again.
Moreover, it seems to use always the same User Agent, no randomization as it should be from version 1.4.2 on.

**To Reproduce**
- Used OS: Debian 10.1
- NodeJs Version (node -v): 14.3.0
- Scraper Version (tiktok-scraper --version): 1.4.2
- CLI or Module_: Module
- Used method: .hashtag(id, options) //Scrape posts from hashtag section (Promise)
- Used options: await TikTokScraper.hashtag('fitness0, { number: 400, asyncScraping: 1 });
- Do you run the scraper through Proxy, VPN, VPS? On a VPS
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! Not applicable
- Preferably provide URL to the profile,hashtag,video and etc page: await TikTokScraper.hashtag('fitness0, { number: 400, asyncScraping: 1 });

Hashtag call always returns zero results.
Moreover, it seems to use always the same User Agent, no randomization as it should be from version 1.4.2 on.

**Screenshots**

![image](https://user-images.githubusercontent.com/4056852/98918341-c9f36800-24cd-11eb-9766-ecff8d1b5972.png)

**Comment by drawrowfly** [comment] 2020-11-12 09:05
You're doing something wrong

App can't have same user-agent by default, it will be always random, you are using old version or own custom user-agent

Closing. Bug can't be reproduced in the latest version

**Closed by drawrowfly** 2020-11-12 09:05 UTC

**Comment by geco** [comment] 2020-11-12 09:30
I think that user agent is random only at library require, but not at every call.
So, if used as a module, it will be always the same at every call inside same node.js instance, perhaps?

**Comment by drawrowfly** [comment] 2020-11-12 10:00
That is correct as it was always before, but i think it will be good idea to add possibility to set random UA on every request as well

Anyway i can't reproduce the issue from mine side, my guess is that is the IP related issue
